// app/layout.tsx (or src/app/layout.tsx)
import type { Metadata } from "next";
import { Geist, Geist_Mono, Golos_Text } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  preload: true,
});

const golos = Golos_Text({
  variable: "--font-golos-text",           // keeps Tailwind option open
  subsets: ["latin", "cyrillic"],          // important for Mongolian
  weight: ["400", "500", "700"],
  display: "swap",
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="mn">
      {/* Make Golos the default text font; Geist Mono available for code */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${golos.variable} antialiased`}
        style={{
          fontFamily:
            "var(--font-golos-text), system-ui, -apple-system, Segoe UI, Roboto, Noto Sans, Ubuntu, Cantarell, Helvetica Neue, Arial, Apple Color Emoji, Segoe UI Emoji",
        }}
      >
        {children}
      </body>
    </html>
  );
}
